document.write("<footer>");
document.write("			<div class=\"wrapper\">");
document.write("			");
document.write("				<ul  class=\"widget-cols clearfix\">");
document.write("					<li class=\"first-col\">");
document.write("						");
document.write("						<div class=\"widget-block\">");
document.write("						");
document.write("						<div id=\"instawidget\">");
document.write("					");
document.write("							<h4>@stretfordstudios INSTAGRAM<\/h4>");
document.write("							<!-- SnapWidget -->");
document.write("");
document.write("<iframe src=\"http:\/\/snapwidget.com\/in\/?u=c3RyZXRmb3Jkc3R1ZGlvc3xpbnw3MHwzfDN8fG5vfDV8bm9uZXxvblN0YXJ0fHllcw==&v=291113\" title=\"Instagram Widget\" allowTransparency=\"true\" frameborder=\"0\" scrolling=\"no\" style=\"border:none; overflow:hidden; width:225px; height:225px\"><\/iframe>");
document.write("<\/div>");
document.write("");
document.write("<div id=\"instawidget2\">");
document.write("							<h4>@stretfordstudios INSTAGRAM<\/h4>");
document.write("							<!-- SnapWidget -->");
document.write("");
document.write("<iframe src=\"http:\/\/snapwidget.com\/in\/?u=c3RyZXRmb3Jkc3R1ZGlvc3xpbnw3MHwzfDN8fG5vfDV8bm9uZXxvblN0YXJ0fHllcw==&v=291113\" title=\"Instagram Widget\" allowTransparency=\"true\" frameborder=\"0\" scrolling=\"no\" style=\"border:none; overflow:hidden; width:150px; height:300px\"><\/iframe>");
document.write("");
document.write("<\/div>");
document.write("							<\/div>");
document.write("						");
document.write("					<\/li>");
document.write("					");
document.write("					<li class=\"second-col\">");
document.write("						");
document.write("						<div class=\"widget-block\">");
document.write("							<h4>Links to Clients\/Associates<\/h4>");
document.write("						<div class=\"recent-post\">");
document.write("							<a href=\"http:\/\/www.getthelabel.com\" class=\"thumb\"><img src=\"img\/GTL.jpg\" alt=\"Get The Label\" \/><\/a>");
document.write("							<div class=\"post-head\">");
document.write("							<a href=\"http:\/\/getthelabel.com\">Get The Label<\/a><span> Discount designer clothing, Up to 75% off mens, womens, boys & girls clothing.<\/span>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("						<div class=\"recent-post\">");
document.write("							<a href=\"http:\/\/www.europeantour.com\" class=\"thumb\"><img src=\"img\/PGA.jpg\" alt=\"Post\" \/><\/a>");
document.write("							<div class=\"post-head\">");
document.write("							<a href=\"http:\/\/www.europeantour.com\">PGA European Tour<\/a><span>European Golf's ruling body and organisers of the 3 leading golf tours in Europe<\/span>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("						<div class=\"recent-post\">");
document.write("							<a href=\"http:\/\/www.dannylowry.co.uk\" class=\"thumb\"><img src=\"img\/DLE.jpg\" alt=\"Post\" \/><\/a>");
document.write("							<div class=\"post-head\">");
document.write("							<a href=\"http:\/\/www.dannylowry.co.uk\">Danny Lowry Entertainments<\/a><span>Leading UK Artist Management & Entertainment Agent<\/span>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("							");
document.write("						<\/div>");
document.write("											");
document.write("					<\/li>");
document.write("					");
document.write("					<li class=\"third-col\">");
document.write("						");
document.write("						<div class=\"widget-block\">");
document.write("							<div id=\"tweets\" class=\"footer-col tweet\">");
document.write("		         				<h4>@stretfordstudio TWITTER<\/h4>");
document.write("		         			");
document.write("<a class=\"twitter-timeline\" href=\"https:\/\/twitter.com\/twitterapi\" data-widget-id=\"349550557117153282\" data-chrome=\"noheader transparent nofooter noscrollbar\" data-link-color=\"#cc0000\"  data-related=\"twitterapi,twitter\" data-aria-polite=\"assertive\" width=\"220\" height=\"220\" lang=\"EN\">Tweets by @stretfordstudio<\/a>");
document.write("<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=\/^http:\/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+\":\/\/platform.twitter.com\/widgets.js\";fjs.parentNode.insertBefore(js,fjs);}}(document,\"script\",\"twitter-wjs\");<\/script>");
document.write("");
document.write("");
document.write("");
document.write("<\/div>");
document.write("		         		<\/div>");
document.write("		         		");
document.write("					<\/li>");
document.write("					");
document.write("					<li class=\"fourth-col\">");
document.write("						");
document.write("						<div class=\"widget-block\"><h4>join our MAILING LIST<\/h4><div id=\"mailinglist\">");
document.write("							");
document.write("<script type=\"text\/javascript\">document.write(unescape(\"%3Cscript src='http\" +  (document.location.protocol == 'https:' ? 's' : '') + \":\/\/www.coffeecup.com\/api\/sdrive\/forms\/form.js?name=email%26slug=251218%26width=200%26height=280%26crossdomains=true%26rand=\" + Math.floor( Math.random() * 1000000000 ) + \"' type='text\/javascript'%3E%3C\/script%3E\"));<\/script>");
document.write("");
document.write("<\/div><\/div>");
document.write("		         		");
document.write("					<\/li>	");
document.write("				<\/ul>				");
document.write("				");
document.write("				");
document.write("				<div class=\"footer-bottom\">");
document.write("				<div class=\"left\">");
document.write("				<h4>Stretford Studios Ltd.<\/h4>");
document.write("							Manor Farm Industrial Estate | Poplar Road | Stretford | Manchester | M32 9AN<br>T: +44 (0)161 864 4367 | E: info@stretfordstudios.co.uk<\/p><\/div>");
document.write("					<div class=\"right\">");
document.write("						<ul id=\"social-bar\">");
document.write("							<li><a href=\"http:\/\/www.facebook.com\/pages\/Stretford-Studios\/510530779051198\"  title=\"Stretford Studios on Facebook\" class=\"poshytip\"><img src=\"img\/social\/facebook.png\"  alt=\"Facebook\" \/><\/a><\/li>");
document.write("							<li><a href=\"https:\/\/twitter.com\/stretfordstudio\" title=\"@stretfordstudio\" class=\"poshytip\"><img src=\"img\/social\/twitter.png\"  alt=\"twitter\" \/><\/a><\/li>");
document.write("							<li><a href=\"https:\/\/plus.google.com\/u\/0\/103390395735106511900\/posts\"  title=\"Google+\" class=\"poshytip\"><img src=\"img\/social\/plus.png\" alt=\"Google plus\" \/><\/a><\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("				");
document.write("			<\/div>");
document.write("		<\/footer>");
document.write("");
