document.write("");
document.write("<html>");
document.write("	");
document.write("");
document.write("<header class=\"clearfix\">");
document.write("		");
document.write("				");
document.write("			<div class=\"wrapper clearfix\">");
document.write("				");
document.write("				<a href=\"index.html\" id=\"logo\"><img  src=\"img\/stu_logo_180.png\" width=\"120px\" alt=\"Stretford Studios Ltd.\"><\/a>");
document.write("				");
document.write("				<div id=\"headerbanner\"><h1>SIGNS. PRINT. DESIGN.<\/h1><br><\/div>");
document.write("				");
document.write("				<nav>");
document.write("					<ul id=\"nav\" class=\"sf-menu\">");
document.write("						<li class=\"current-menu-item\"><a href=\"index.html\">HOME<\/a><\/li>");
document.write("						<li><a href=\"#\">SIGNS<\/a>");
document.write("							<ul>");
document.write("								<li><a href=\"signs-and-fascias.html\">Fascias & Shop Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Estate Agents Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Safety Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Noticeboards<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Hotel Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Lamppost Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">3D & Illuminated Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Projection & Swing Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">School Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Office Signs<\/a><\/li>");
document.write("								<li><a href=\"signs-and-fascias.html\">Golf\/Sports Signage<\/a><\/li>");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("");
document.write("						<li><a href=\"#\">PRINT<\/a>");
document.write("							<ul>");
document.write("								<li><a href=\"posters.html\">Posters<\/a><\/li>");
document.write("								<li><a href=\"banners.html\">Banners & Flags<\/a><\/li>");
document.write("								<li><a href=\"window-graphics.html\">Window Graphics<\/a><\/li>");
document.write("								<li><a href=\"canvas.html\">Canvas Prints<\/a><\/li>");
document.write("								<li><a href=\"flyers.html\">Business Stationery<\/a><\/li>");
document.write("								<li><a href=\"flyers.html\">Flyers, Leaflets & Brochures<\/a><\/li>");
document.write("								<li><a href=\"pos.html\">Point of Sale<\/a><\/li>");
document.write("								<li><a href=\"wallart.html\">Wall Paper & Wall Art<\/a><\/li>");
document.write("							");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("						<li><a href=\"#\">VINYL<\/a>");
document.write("							<ul>");
document.write("								<li><a href=\"vinyl.html\">Computer Cut Vinyl<\/a><\/li>");
document.write("								<li><a href=\"wallart.html\">Vinyl Wall Art & Graphics<\/a><\/li>");
document.write("							");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("						<li><a href=\"#\">VEHICLE GRAPHICS<\/a>");
document.write("							<ul>");
document.write("								");
document.write("								<li><a href=\"vehicle-graphics.html\">Vehicle Graphics & Branding<\/a><\/li>");
document.write("								<li><a href=\"vehicle-graphics.html\">Colour Change & Partial Wraps<\/a><\/li>");
document.write("								<li><a href=\"vehicle-graphics.html\">Printed Vehicle Wraps<\/a><\/li>");
document.write("								<li><a href=\"vehicle-graphics.html\">Removable Vehicle Signage<\/a><\/li>");
document.write("							");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("						<li><a href=\"#\">DESIGN<\/a>");
document.write("							<ul>	");
document.write("								<li><a href=\"design.html\">Branding & Corporate Identity<\/a><\/li>");
document.write("								<li><a href=\"design.html\">Artwork and Type Setting<\/a><\/li>");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("						<li><a href=\"contact.html\">CONTACT<\/a><\/li>");
document.write("						<li><a href=\"/blog\">BLOG & BUYERS GUIDE<\/a><\/li>");
document.write("					<\/ul>");
document.write("					<div id=\"combo-holder\"><\/div>");
document.write("				<\/nav>");
document.write("			<\/div>");
document.write("		<\/header>");
document.write("<\/html>");
